# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'TTS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Vonage Video SDK
  pod 'OpenTok', '~> 2.27'

  # Vonage Media Transformers (for background replacement and custom transformers)
  pod 'VonageClientSDKVideoTransformers', '~> 2.27'

end
